Open sourcing and quality checks
NHSDigital/software-engineering-quality-framework pull request #147
Opened 2021-06-07 11:12 UTC by andyblundell

2021-06-16 10:04 UTC, andyblundell commented
From James: secret scanning should be a green

2021-06-16 11:18 UTC, edhiley commented on quality-checks.md
> +All code should be treated kindly, but code that is being published incurs additional considerations: for example, it's never good to include credentials and other secrets in source code, but the imp
All code should be treated equally?
I think it's worth defining what "published" means - as in, be clear we mean giving public access to the code.  Agree with the assigned minimums.

2021-06-16 11:18 UTC, edhiley requested changes
As per comments.

2021-07-26 10:15 UTC, andyblundell commented on quality-checks.md
> +All code should be treated kindly, but code that is being published incurs additional considerations: for example, it's never good to include credentials and other secrets in source code, but the imp
@edhiley I've tweaked the words a bit - how does that look to you now?

2021-07-26 10:35 UTC, iw-ezequiel commented on quality-checks.md
> +Therefore, for published code, the following minimums are recommended:
Would the choice of word here in "recommend" be sufficient? It would leave the door open to someone dismissing the recommendation. "required" is quite stronger but we could perhaps caveat that any deviations would need good reason?

2021-08-18 11:22 UTC, merged