README file for git-secrets tool
NHSDigital/software-engineering-quality-framework pull request #156
Opened 2021-07-16 12:30 UTC by iw-ezequiel

2021-07-23 16:24 UTC, andyblundell requested changes

2021-07-23 16:24 UTC, andyblundell commented on tools/nhsd-git-secrets/README.md
> +# Getting to green
Let's link to the definition in quality-check.md

Otherwise, all good! Thanks

2021-07-26 07:05 UTC, iw-ezequiel commented on tools/nhsd-git-secrets/README.md
> +# Getting to green
All done, thanks Andy

2021-07-26 07:34 UTC, andyblundell approved these changes

2021-07-26 07:34 UTC, merged