Align with our own guidance for codeowners team name
NHSDigital/software-engineering-quality-framework pull request #223
Opened 2021-11-08 18:07 UTC by andyblundell

2021-11-08 18:08 UTC, andyblundell commented
As things stand we have 2 codeowners files, but let's make sure the new team works before we do anything about that

2021-11-08 18:35 UTC, stefaniuk commented
@andyblundell Sorry, I'm not sure why I haven't spotted the one in the root directory. Would it be a good idea to move it to the `.github` directory so anything specific to GitHub functionality can be placed there in the dedicated folder? Just a thought.

2021-11-09 07:26 UTC, andyblundell commented
@stefaniuk good call - I *think* a copy in .github takes precedent over a copy in the root folder, so yep .github is the better place for it. Looking at your copy again, I think we've ended up with a global code owner (from the original file) plus some specific code owner patterns (from your file). Let's revert to a single file (now in .github), but I'm not sure if those new patterns are actually doing anything though, given they all point to the same team as the global entry?

2021-11-09 08:19 UTC, andyblundell commented
I've removed the CODEOWNERS file from the root folder, having copied the default owner pattern to the .github copy of the file

But unless I'm missing something the new patterns are redundant, since they all point to the same team as the default pattern...

2021-11-09 08:28 UTC, stefaniuk requested changes

2021-11-09 08:28 UTC, stefaniuk commented on .github/CODEOWNERS
> +@NHSDigital/software-engineering-quality-framework-code-owners
We may need a '*' character at the beginning of this line if we would like to enforce review of any change in the repo be the 'code-owners'.

2021-11-09 08:28 UTC, stefaniuk commented on .github/CODEOWNERS
> +# Owners for specific areas in the repo
Yes, that's right. If the above is in place that block is redundant.

2021-11-09 08:42 UTC, andyblundell commented on .github/CODEOWNERS
> +# Owners for specific areas in the repo
Silly me - thanks :)

2021-11-09 08:45 UTC, andyblundell commented on .github/CODEOWNERS
> +@NHSDigital/software-engineering-quality-framework-code-owners
My previous "silly me" was supposed to be here :)

2021-11-09 08:45 UTC, andyblundell commented on .github/CODEOWNERS
> +# Owners for specific areas in the repo
I'v removed those extra blocks - we can add more later if we do want different owners for different sections of the project

2021-11-09 08:50 UTC, iw-ezequiel approved these changes

2021-11-09 08:54 UTC, merged