222 contributing guidelines
NHSDigital/software-engineering-quality-framework pull request #230
Opened 2021-11-10 11:38 UTC by iw-ezequiel

2021-11-10 12:31 UTC, andyblundell requested changes

2021-11-10 12:31 UTC, andyblundell commented on .github/workflows/action.yml
> +    - uses: actions/checkout@main
I need to remind myself what this line is doing but I think it's saying we fetch from the master branch of github-action-markdown-link-check (which is still called master)

2021-11-10 12:31 UTC, andyblundell commented on .github/CONTRIBUTING.md
> +Thank you for interest in improving the framework.
for "your" interest?

2021-11-10 12:31 UTC, andyblundell commented on .github/CONTRIBUTING.md
> +# Welcome to the Engineering Framework contributors guide
Shall we include something along the lines of: this describes how we go about engineering, but not operational NHSD things like like how we structure our NHSD teams, details of NHSD roles & responsibilities, etc (so that others can use this guidance)?

2021-11-10 12:34 UTC, iw-ezequiel commented on practices/security.md
> +The [OWASP Web Security Testing Guide](https://github.com/OWASP/wstg/tree/main/document) is an extensive and wide-reaching reference on how to test for security, including examining the software deli
Correct - they haven't changed it and I did in the previous commit, it broke :D

2021-11-10 12:34 UTC, iw-ezequiel commented on practices/security.md
> +- **Enforce** infrastructure security (e.g. [Azure Policy](https://docs.microsoft.com/en-us/azure/governance/policy/overview), [AWS Config](https://aws.amazon.com/config/)) and validate it (e.g. [Sco
Same!

2021-11-10 12:34 UTC, iw-ezequiel commented on .github/workflows/action.yml
> +    - uses: actions/checkout@main
I thought this was checking out _our_ main branch but you may be right here

2021-11-10 12:35 UTC, iw-ezequiel commented on .github/CONTRIBUTING.md
> +Thank you for interest in improving the framework.
Doh, so much for saying check your spelling lol

2021-11-10 15:03 UTC, andyblundell commented on .github/CONTRIBUTING.md
> + * Nothing in it should be confidential, private to NHSD or include any personal data.
Possibly broken markdown formatting - is that a single space?

I won't say it... :)

2021-11-10 16:07 UTC, iw-ezequiel commented on .github/CONTRIBUTING.md
> + * Nothing in it should be confidential, private to NHSD or include any personal data.
Actually this one should be fine, it's to get a second level of bullet points (if you're thinking of tabs vs spaces though, yes let's please not go anywhere near that lol)

2021-11-11 15:57 UTC, andyblundell commented on .github/CONTRIBUTING.md
> + * Nothing in it should be confidential, private to NHSD or include any personal data.
Ah but single space doesn't indent the bullets - they're currently all at the same level :)

2021-11-11 16:51 UTC, iw-ezequiel commented on .github/CONTRIBUTING.md
> + * Nothing in it should be confidential, private to NHSD or include any personal data.
Ahh this is Github (or Atom...) being naughty, the preview plugin in Atom says all good!

2021-11-11 17:41 UTC, andyblundell requested changes

2021-11-11 17:41 UTC, andyblundell commented on README.md
> +See our (contributor's guide)[./github/CONTRIBUTING.md]
The brackets are the wrong way around :)

2021-11-11 17:43 UTC, iw-ezequiel commented on README.md
> +See our (contributor's guide)[./github/CONTRIBUTING.md]
I'm not really doing well with this am I! Embarrassing stuff. Thanks for catching it!

2021-11-11 17:51 UTC, andyblundell approved these changes
:)

2021-11-11 17:51 UTC, merged