Issue #244  Initial draft of performance testing page including summarized case study of DSPT use of APDEX
NHSDigital/software-engineering-quality-framework pull request #245
Opened 2022-02-16 17:12 UTC by chrisclarknhsnet

As per discussions with Andy

2022-02-16 18:21 UTC, andyblundell requested changes
This is great - will re-review tomorrow, in the meantime have suggested one extra section. Is there any code from the case study that would be worth sharing? Maybe the Jenkins config snippet? Obviously your jmeter config is bespoke.

2022-02-16 18:21 UTC, andyblundell commented on practices/performancetesting.md
> +### A case study (approach)
Please could you add a brief section on the *impact* in this case study, e.g. perhaps a process that used to take X hours of person time and therefore was only run every X weeks now requires no human intervention, and is run every day/week/release-candidate/whatever?

2022-02-17 16:58 UTC, stefaniuk submitted a review, later dismissed
Would it be ok to change the location of the new images and the naming convention for the files, please? E.g. `practices/images/dspt-case-study-aggregated-apdex-scores.png`

2022-02-17 16:58 UTC, stefaniuk commented on practices/performancetesting.md
> +We therefore wrote a Python program which would take the raw JMeter results file (a sample of shown below) and using regular expressions to group results by thread names matching a Mr Man scenario, w
Would you be happy to include your Python code and configuration that could be helpful to others as part of the case study?

2022-02-17 16:59 UTC, stefaniuk commented
This case study reads really well. Nice work!

2022-02-17 17:38 UTC, andyblundell commented on practices/performancetesting.md
> +<div style="float:right">
I'm not sure this is rendering how it was supposed to...?

2022-02-17 18:04 UTC, chrisclarknhsnet commented on practices/performancetesting.md
> +<div style="float:right">
Amended to just use simple mark up, that'll teach me,

2022-02-17 18:07 UTC, chrisclarknhsnet commented on practices/performancetesting.md
> +We therefore wrote a Python program which would take the raw JMeter results file (a sample of shown below) and using regular expressions to group results by thread names matching a Mr Man scenario, w
Yes, although I probably want to give it a quick sanity check first as was hacking it around a bit a few weeks ago.
Will look to add this early next week.

2022-02-17 19:10 UTC, andyblundell commented on practices/performancetesting.md
> +We therefore wrote a Python program which would take the raw JMeter results file (a sample of shown below) and using regular expressions to group results by thread names matching a Mr Man scenario, w
Converted to https://github.com/NHSDigital/software-engineering-quality-framework/issues/246 for the code/config to be added (hopefully) later - will resolve this comment in the meantime

@stefaniuk FYI

2022-02-18 07:34 UTC, andyblundell commented on practices/performance-testing.md
> +### A case study - impact
@chrisclarknhsnet are you happy with this final section please? I think it needed a summary / impact to close, and I've tried to paraphrase content from the case study - hopefully I've not misrepresented you!

2022-02-18 09:33 UTC, chrisclarknhsnet commented on practices/performance-testing.md
> +### A case study - impact
Yep that's fine Andy

2022-05-03 16:24 UTC, andyblundell approved these changes

2022-05-03 16:24 UTC, merged