Update continuous integration practice
NHSDigital/software-engineering-quality-framework pull request #268
Opened 2022-07-28 16:23 UTC by stefaniuk

Changes:
- Update continuous integration practice document
- Add ToC to all docs in the practice directory

2022-08-05 07:43 UTC, andyblundell requested changes
All looks good - a few suggested tweaks to the list you've incorporated

2022-08-05 07:43 UTC, andyblundell commented on practices/continuous-integration.md
> +| Result publishing             | Are the results from your build (success/error/warn) clear and concise?  Can you always tell exactly what caused a build to fail? Do you get spammed with unnecessary
Can we rephrase "telling Test that a build is ready" pls - sounds a bit hand-off-y :)

2022-08-05 07:43 UTC, andyblundell commented on practices/continuous-integration.md
> +| Effectiveness and Maintenance | Despite your fancy build pipeline, are you still seeing high bug/error/security/etc. rates in production? Are you spending too much team effort on maintaining your p
Can we reword "fancy" pls?

2022-08-05 07:43 UTC, andyblundell commented on practices/continuous-integration.md
> +| Load tests               | Do you frequently check that your application can cope with as-live load? Do you know how much increased load you can handle? Are these tests fully automated as part of y
Let's drop the Texan reference :)

2022-08-05 07:43 UTC, andyblundell commented on practices/continuous-integration.md
> +| Pipeline steps           | Things to consider
Lots of overlap with the quality-checks page, probably worth adding a link across (or trying to combine the lists)?

2022-08-05 07:43 UTC, andyblundell commented on practices/continuous-integration.md
> +| Tech RAG checking        | Have your frameworks and technologies been deprecated by NHSD? Do you currently check your application against the NHSD Tech RAG? If so, how? Does the tooling integrate d
Tech RAG == Tech radar?

2022-08-06 09:13 UTC, stefaniuk commented on practices/continuous-integration.md
> +| Result publishing             | Are the results from your build (success/error/warn) clear and concise?  Can you always tell exactly what caused a build to fail? Do you get spammed with unnecessary
I removed this sentence.

2022-08-06 09:14 UTC, stefaniuk commented on practices/continuous-integration.md
> +| Effectiveness and Maintenance | Despite your fancy build pipeline, are you still seeing high bug/error/security/etc. rates in production? Are you spending too much team effort on maintaining your p
Reworded to "Despite having a robust build pipeline"

2022-08-06 09:15 UTC, stefaniuk commented on practices/continuous-integration.md
> +| Load tests               | Do you frequently check that your application can cope with as-live load? Do you know how much increased load you can handle? Are these tests fully automated as part of y
The Texan reference dropped

2022-08-06 09:16 UTC, stefaniuk commented on practices/continuous-integration.md
> +| Tech RAG checking        | Have your frameworks and technologies been deprecated by NHSD? Do you currently check your application against the NHSD Tech RAG? If so, how? Does the tooling integrate d
Done

2022-08-06 09:19 UTC, stefaniuk commented on practices/continuous-integration.md
> +| Pipeline steps           | Things to consider
There is more work planned in this area ("continuous integration") as we are reviewing our practice with one or two of the programmes. The intention is to incorporate any given feedback here. This should follow as a separate PR. I'll bear that in mind to link to the quality checks page.

2022-08-11 19:31 UTC, merged