Added detail on code repository commit signing, and on OIDC federated auth
NHSDigital/software-engineering-quality-framework pull request #274
Opened 2022-09-13 15:04 UTC by patrickmoore-nc

[Issue 273 raised](https://github.com/NHSDigital/software-engineering-quality-framework/issues/273)

- Added an explanation to **practices/security-repository.md** for why commit signing is needed since many developers are unaware that authentication is completely separate from identity when using git.
- Created **practices/guides/commit-signing.md**, linked to from the above, to show worked examples of configuring commit signing - from human contributors, and from pipeline bots.
- Added to **tools/nhsd-git-secrets/README.md** a suggestion to use OIDC federated authentication to Cloud providers, to avoid storing credentials in repository secrets

2022-09-13 20:04 UTC, stefaniuk requested changes
I put some comments on this PR and requested changes but they are rather syntactic sugar. This is really a high-quality and well-thought addition to the framework. Thanks for that!

2022-09-13 20:09 UTC, stefaniuk commented on practices/guides/commit-signing.md
> +  echo "Encrypted GPG secret key found in the AFT Parameter Store, enabling GitHub commmit signing"
The reference to AFT seems to be coincidental in this context.

2022-09-14 09:07 UTC, patrickmoore-nc commented on practices/guides/commit-signing.md
> +  echo "Encrypted GPG secret key found in the AFT Parameter Store, enabling GitHub commmit signing"
Correct, that has leaked in there from the origins of that code, will amend.

2022-09-14 09:07 UTC, patrickmoore-nc commented on practices/guides/commit-signing.md
> +# create SSH identity for connecting to GitHub
Can do, will amend.

2022-09-14 09:08 UTC, patrickmoore-nc commented on practices/guides/commit-signing.md
> +The cryptographic libraries in the default Amazon Linux 2 distro are very old, and do not support elliptic curve cryptography. When using pre-existing solution elements updating the build container i
Will amend this to make the point that it really must be 4096

2022-09-14 09:12 UTC, patrickmoore-nc commented on practices/guides/commit-signing.md
> +Usually it will fail because the name or email don't quite match up with the values use to generate the GPG key, so git cannot auto-select a key. However you are able to [force a choice of signing ke
Not sure about this. Really, by forcing the key ID it's kind of like committing as another user - the whole thing we're trying to prevent. Ideally the key should closely match the email and username of the current git user.

2022-09-14 11:19 UTC, patrickmoore-nc commented on tools/nhsd-git-secrets/README.md
> +# Consider using OIDC instead of secrets
I think that needs running again since my new commits.

2022-09-14 11:19 UTC, patrickmoore-nc commented on practices/guides/commit-signing.md
> +- From workstations:
Done

2022-09-14 11:29 UTC, patrickmoore-nc commented on practices/guides/commit-signing.md
> +- Accept the defaults, Curve 25519 etc.
Unfortunately the Git-for-Windows integrated version of GPG doesn't yet support elliptic curve, so my submitted Windows guide states to use RSA and override 3072 to 4096 bit (the minimum supported by GitHub).

Though I'm sure people could download a newer GPG separately, I think that would complicate the guide substantially. There is a lower friction with using the integrated versions. Hopefully support is not far off.

2022-09-14 15:22 UTC, patrickmoore-nc commented on tools/nhsd-git-secrets/README.md
> +# Consider using OIDC instead of secrets
I have also added Windows instructions to the Commit Signing guide.

2022-09-15 08:03 UTC, stefaniuk commented on practices/guides/commit-signing.md
> +Usually it will fail because the name or email don't quite match up with the values use to generate the GPG key, so git cannot auto-select a key. However you are able to [force a choice of signing ke
Ok, I think I see your point. However, I had to ponder over it for a moment as it requires some prior knowledge of how this mechanism works. Will you be able to expand on it a bit, please? E.g. explaining why you don't recommend enforcing specific key to be in use.

2022-09-15 08:51 UTC, stefaniuk commented on tools/nhsd-git-secrets/README.md
> +# Consider using OIDC instead of secrets
I rerun the checks. There might be more formatting needed. To make life easier for us I may push a local git hook that does precisely the same thing as the github action.

2022-09-16 11:53 UTC, stefaniuk commented on tools/nhsd-git-secrets/README.md
> +# Consider using OIDC instead of secrets
@patrickmoore-nc Please, could you update your fork and check if the local git hook that has just been merged is helpful with addressing the Markdown formatting issues?

2022-09-16 16:29 UTC, patrickmoore-nc commented on tools/nhsd-git-secrets/README.md
> +# Consider using OIDC instead of secrets
I've been committing through the GitHub website since it's easier to preview the Markdown that way. I think I have dealt with most of the formatting issues reported though.

2022-09-16 17:06 UTC, patrickmoore-nc commented on practices/guides/commit-signing.md
> +Usually it will fail because the name or email don't quite match up with the values use to generate the GPG key, so git cannot auto-select a key. However you are able to [force a choice of signing ke
Git looks for a key based on the the email or the name in a similar manner to the behaviour of the underlying gpg tool:

```
gpg --list-keys "patrickmoore-nc"
```

If a single key is offered, git will use that to sign the commit. The scenarios for an explicit override would be that you used a name which is different from the actual GitHub username (undesirable), or that you have several keys in the keyring with that same name (e.g. an older expired one or something like that, also undesirable).

Since forcing the use of a particular key ID requires more explanation, as you need to retrieve its ID, I think it needlessly complicates the instructions, which can put people off using this mechanism. Simplicity here aids adoption, which was the motivator for writing this up after all. By linking to GitHub's own instructions for overriding the key selection, I do a least alert the reader that it's possible - it can be useful for debugging.

2022-09-26 09:52 UTC, patrickmoore-nc commented
Corrected markdown validation issues in **tools/nhsd-git-secrets/README.md**

2022-09-26 10:30 UTC, patrickmoore-nc commented
More fixes to **tools/nhsd-git-secrets/README.md**
Most of these errors are for content I did not change.

2022-09-27 09:54 UTC, patrickmoore-nc commented
The markdown looks to be compliant now, I think it just needs you re-approve the requested changes since new commits have occurred since they were marked closed.

2022-09-28 07:07 UTC, stefaniuk approved these changes
LGTM!

2022-09-28 07:12 UTC, merged