ignoring link checking for Azure links and updating OWASP Zap link
NHSDigital/software-engineering-quality-framework pull request #308
Opened 2023-10-11 19:46 UTC by walteck

2023-10-13 07:43 UTC, stefaniuk requested changes

2023-10-13 07:43 UTC, stefaniuk commented on practices/cloud-services.md
> +  - Favour global-scoped (e.g. [CloudFront](https://aws.amazon.com/cloudfront/) or [Front Door](https://azure.microsoft.com/en-gb/pricing/details/frontdoor/)) or region-scoped services (e.g. [S3](htt
These issues seem to be intermittent and are not specific to these links. Can we set the [`markdown-check-links`](https://github.com/NHSDigital/software-engineering-quality-framework/blob/main/.github/workflows/markdown-check-links.yml) workflow to continue on error and use it for feedback only?

2023-10-16 13:35 UTC, regularfry commented
@walteck you might want [this](https://github.com/NHSDigital/software-engineering-quality-framework/pull/310), which seems to be a bit more reliable.  I'll be interested to see if it becomes intermittent over time.

Two observations at this point:

1. We are tying correctness of our own changes to state we don't control. Someone else can make our pipeline break and that's not great. But also it's a check at a single point in time, where what we really want is continuous monitoring.
2. The failures we have seen are false positives.

2024-11-06 16:25 UTC, walteck commented
These changes have already made it into main through another route therefore I would propose we close this PR and branch. @regularfry any objections?

2024-11-06 16:33 UTC, regularfry commented
Yes, these are fixed elsewhere.

2024-11-06 16:33 UTC, closed without merging