fleshed out test automation working group
NHSDigital/software-engineering-quality-framework pull request #45
Opened 2020-09-16 09:27 UTC by dlavender4

2020-09-16 10:47 UTC, andyblundell requested changes
Hiya - all looks good, one small request about dropping the ABR reference pls

2020-09-16 10:47 UTC, andyblundell commented on communities/pd-test-automation-working-group.md
> +## Time Booking
Can we drop this section please, and mention it in the first session instead? Just because this is public, it's a bit internal-NHSD-esque

2020-09-16 10:47 UTC, andyblundell commented on communities/pd-test-automation-working-group.md
> +## Time Booking
When I say "this section" I just mean the time booking ABR reference :)

2020-09-17 13:38 UTC, andyblundell submitted a review, later dismissed

2020-09-17 13:44 UTC, ivorc reviewed
Tiny suggestions.

2020-09-17 13:44 UTC, ivorc commented on communities/pd-test-automation-working-group.md
> +* [dlavender4](https://github.com/dlavender4) will be coordinator initially
For consistency, could change to:
```suggestion
* David Lavender [dlavender4](https://github.com/dlavender4) will be coordinator initially
```

2020-09-17 13:44 UTC, ivorc commented on communities/pd-test-automation-working-group.md
> +* Should include a mix of backgrounds: Dev, DevOps, Test, Assurance, etc.
Evil etc
```suggestion
* Should include a mix of backgrounds including Dev, DevOps, Test and Assurance.
```

2020-09-17 13:44 UTC, ivorc commented on communities/pd-test-automation-working-group.md
> +* Should include people from as many teams as possible
```suggestion
* Should include people from a representative spread of teams
```

2020-09-17 13:44 UTC, ivorc commented on communities/pd-test-automation-working-group.md
> +* Any member can contribute to the backlog. This could be show-and-tells of tools or approaches; queries about how to do something; curation of a Principal; talking about an organisation-wide policy;
Principle, not principal
```suggestion
* Any member can contribute to the backlog. This could be show-and-tells of tools or approaches; queries about how to do something; curation of a principle; talking about an organisation-wide policy; etc.
```

2020-09-17 14:01 UTC, ivorc approved these changes

2020-09-17 14:02 UTC, merged